### Global gh-pages pre-amble
safe: true
lsi: false
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge


### The following properties will change on a project-by-project basis

# Context path in the remote website (usually /<project>), will be prepended to absolute URLs for static resources
baseurl: /spring-data

# Name of the project for display in places like page titles
name: Spring Data

# ID of the project in the metadata API at spring.io (if this is not a
# valid project ID the javascript widgets in the home page will not work)
project: spring-data

# Project github URL
github_repo_url: http://github.com/spring-projects/spring-data

# If you want to include a custom pom.xml or gradle template set these value to true and add _include files
custom_pom_template: true
custom_gradle_template: true


### The following properties are constant for most projects

spring_site_url: https://spring.io
main_site_url: http://springdev.io
projects_site_url: http://projects.springdev.io
questions_url: http://spring.io/questions
